name: MSRV

on:
  push:
    paths:
      - '.github/workflows/msrv.yml'
  pull_request:
    paths:
      - '.github/workflows/msrv.yml'
  schedule:
    - cron: '0 15 1 * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  msrv:
    name: cargo msrv (${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [linux-x86_64, linux-arm64]
        include:
          - os: linux-x86_64
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: linux-arm64
            runner: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-msrv
      - run: cargo msrv find --all-features --target ${{ matrix.target }} --output-format json
